[project]
name = 'Reality-Simulation-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cross-simulation-asset]
path = 'contracts/cross-simulation-asset.clar'
clarity_version = 2
epoch = 2.5

[contracts.experience-licensing]
path = 'contracts/experience-licensing.clar'
clarity_version = 2
epoch = 2.5

[contracts.simulation-creation]
path = 'contracts/simulation-creation.clar'
clarity_version = 2
epoch = 2.5

[contracts.simulation-stability]
path = 'contracts/simulation-stability.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
